name: Deploy after merge into staging
on:
  push:
    branches:
      - staging

jobs:
  deploy-after-merge-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Testing bash
        id: shouldDeploy
        run: |
          echo '${{ toJSON(github.event) }}' 
          echo '${{ toJSON(github) }}'
