name: Deploy after merge into staging
on:
  push:
    branches:
      - staging

jobs:
  deploy-after-merge-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Testing bash - Event
        id: shouldDeploy
        run: |
          echo '${{ toJSON(github.event) }}' 
          echo '${{ toJSON(github) }}'
      - name: Trigger if it is a change from person
        if: github.event.commits[0].commiter.name != 'GitHub'
        run: |
          echo 'No commiter from github, should deploy'

      - name: Trigger anyway
        if: github.event.commits[0].commiter.name != 'GitHub'
        run: |
          echo 'Trigger anyway'

      - name: Get summary of changes
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: https://helpers.roihunter.com/helpers/releaser/product-images-cache/compare/staging...dev
          configuration: '{ "method": "GET", "headers": {"Authorization": "${{ secrets.HELPERS_AUTH }}"} }'
          format: txt

      - name: See changes
        run: |
          echo '${{ env.fetch-api-data }}'
          echo '${{ toJSON(env.fetch-api-data) }}'
