name: Dev -> Staging
on:
  push:
    branches:
      - dev
jobs:
  dev-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      - name: Testing bash
        id: shouldDeploy
        run: |
          echo '${{ toJSON(github.event) }}' 
          echo '${{ toJSON(github.event.pull_request) }}'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch: dev
          title: Dev -> Staging
          body: "review this please"

  simulate-deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    needs: dev-to-staging
    steps:
      - uses: ./.github/workflows/staging-deploy.yml@staging
