name: Master deploy
on:
  # push:
  #   branches:
  #     - master
  workflow_call:
  workflow_dispatch:
jobs:
  simulate-deploy-master:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deploy finished on master

      - name: Testing bash
        id: shouldDeploy
        run: |
          echo '${{ toJSON(github.event) }}' 
          echo '${{ toJSON(github.event.pull_request) }}'
