on:
  pull_request:
    types:
      - closed

    branches:
      - staging

jobs:
  check-if-merged-and-deploy:
    if: github.event.pull_request.merged
    uses: ./.github/workflows/staging-deploy.yml
