name: Staging deploy
on:
  workflow_call:
  # push:
  #   branches:
  #     - staging
  workflow_dispatch:
jobs:
  simulate-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deploy finished

      - name: Testing bash
        id: shouldDeploy
        run: |
          echo '${{ toJSON(github.event) }}' 
          echo '${{ toJSON(github) }}'
