name: Staging -> Master
on:
  push:
    branches:
      - staging
jobs:
  staging-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Reset promotion branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch: staging
          title: Staging -> Production
          body: "review this please to production"

      - name: Find comment
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          comment-author: "github-actions[bot]"

      - name: Create or update comment
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: |
            test yeah
          edit-mode: replace

      - name: Echo CPR
        run: echo ${{ toJSON(steps.cpr) }}
