name: Staging deploy automatic labels
on:
  pull_request:
    types:
      - labeled

    branches:
      - staging

jobs:
  simulate-deploy-staging-auto:
    if: contains(fromJson('["downmerge", "upmerge"]'), github.event.label.name)
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deploy finished
