name: Staging deploy
on:
  push:
    branches:
      - staging
jobs:
  simulate-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deploy finished

      - name: Testing bash
        id: shouldDeploy
        run: |
          echo '${{ toJSON(github.event) }}' 
          echo '${{ toJSON(github.event.pull_request.merged) }}'
          echo test without json '${{ github.event.pull_request.merged }}'
          echo test without json and string ${{ github.event.pull_request.merged }}
